"""Add is_verified field to User model

Revision ID: 389d68cd8c46
Revises: 3784227a6d31
Create Date: 2024-06-03 15:00:07.255311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389d68cd8c46'
down_revision = '3784227a6d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='0'))
    # Set the default to False explicitly
    op.execute('UPDATE user SET is_verified = 0')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_verified', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
